In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\chitt\OneDrive\Desktop\Smart_Road_Safety_Project\data\indian_roads_dataset.csv")
df

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,Bangalore,Karnataka,13.092276,77.599571,2022-09-29,3:00,3,Thursday,0,...,high,31,low,distraction,minor,3,2,0,NaN,0.10
19996,19996,Chennai,Tamil Nadu,13.172928,80.157062,2023-11-25,1:00,1,Saturday,1,...,high,20,low,distraction,major,4,2,0,NaN,0.10
19997,19997,Chennai,Tamil Nadu,12.997170,80.150724,2022-06-18,15:00,15,Saturday,1,...,high,22,low,weather,minor,3,3,0,NaN,0.10
19998,19998,Kolkata,West Bengal,22.454882,88.322213,2023-03-12,4:00,4,Sunday,1,...,high,33,low,poor road,minor,1,0,0,NaN,0.10
19999,19999,Delhi,Delhi,28.510266,77.065301,2024-07-05,23:00,23,Friday,0,...,low,39,high,overspeeding,minor,4,2,0,NaN,0.65

In [3]:
df.isnull().sum()

accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64

In [4]:
df['festival'] = df['festival'].fillna('No Festival')

In [5]:
df['date'] = pd.to_datetime(df['date'])

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day

df.drop('date', axis=1, inplace=True)

In [6]:
df.head()

,accident_id,city,state,latitude,longitude,time,hour,day_of_week,is_weekend,road_type,...,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score,year,month,day
0,0,Pune,Maharashtra,18.680827,73.930388,5:00,5,Sunday,1,highway,...,weather,fatal,2,2,0,No Festival,0.85,2023,10,22
1,1,Mumbai,Maharashtra,18.817732,72.790846,4:00,4,Sunday,1,urban,...,weather,major,4,3,0,No Festival,0.10,2023,5,21
2,2,Mumbai,Maharashtra,19.096889,72.819424,13:00,13,Wednesday,0,urban,...,weather,minor,1,1,0,No Festival,0.45,2024,7,10
3,3,Chandigarh,Punjab,30.787805,76.847507,11:00,11,Sunday,1,urban,...,distraction,minor,5,2,0,No Festival,0.65,2025,3,30
4,4,Chennai,Tamil Nadu,12.965155,80.283313,16:00,16,Thursday,0,highway,...,distraction,minor,2,1,0,No Festival,0.10,2024,1,25

In [7]:
df.drop('time', axis=1, inplace=True)
df.drop('accident_id', axis=1, inplace=True)
df.drop('is_weekend',axis=1,inplace=True)

In [8]:
df.to_csv("../data/road_safety_visualization.csv", index=False)

In [9]:
print(df.columns.tolist())

['city', 'state', 'latitude', 'longitude', 'hour', 'day_of_week', 'road_type', 'lanes', 'traffic_signal', 'weather', 'visibility', 'temperature', 'traffic_density', 'cause', 'accident_severity', 'vehicles_involved', 'casualties', 'is_peak_hour', 'festival', 'risk_score', 'year', 'month', 'day']

In [10]:
df_ml = df.copy()

In [11]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = [
    'city','state','road_type',
    'traffic_signal','weather','visibility',
    'traffic_density','cause',
    'accident_severity','festival','day_of_week'
]

for col in categorical_cols:
    le = LabelEncoder()
    le.fit(df_ml[col])
    
    print(f"\n{col}")
    for i, value in enumerate(le.classes_):
        print(f"{value} -> {i}")

city
Bangalore -> 0
Chandigarh -> 1
Chennai -> 2
Delhi -> 3
Hyderabad -> 4
Kolkata -> 5
Mumbai -> 6
Pune -> 7

state
Delhi -> 0
Karnataka -> 1
Maharashtra -> 2
Punjab -> 3
Tamil Nadu -> 4
Telangana -> 5
West Bengal -> 6

road_type
highway -> 0
rural -> 1
urban -> 2

traffic_signal
0 -> 0
1 -> 1

weather
clear -> 0
fog -> 1
rain -> 2

visibility
high -> 0
low -> 1
medium -> 2

traffic_density
high -> 0
low -> 1
medium -> 2

cause
distraction -> 0
drunk driving -> 1
overspeeding -> 2
poor road -> 3
weather -> 4

accident_severity
fatal -> 0
major -> 1
minor -> 2

festival
Diwali -> 0
Eid -> 1
Holi -> 2
New Year -> 3
No Festival -> 4

day_of_week
Friday -> 0
Monday -> 1
Saturday -> 2
Sunday -> 3
Thursday -> 4
Tuesday -> 5
Wednesday -> 6

In [12]:
for col in categorical_cols:
    df_ml[col] = le.fit_transform(df_ml[col])

In [13]:
df_ml.dtypes

city                   int64
state                  int64
latitude             float64
longitude            float64
hour                   int64
day_of_week            int64
road_type              int64
lanes                  int64
traffic_signal         int64
weather                int64
visibility             int64
temperature            int64
traffic_density        int64
cause                  int64
accident_severity      int64
vehicles_involved      int64
casualties             int64
is_peak_hour           int64
festival               int64
risk_score           float64
year                   int32
month                  int32
day                    int32
dtype: object

In [14]:
df_ml.to_csv("../data/cleaned_road_safety_ml.csv", index=False)