# Data Understanding

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Data Collection
df=pd.read_csv(r"C:\Users\chitt\OneDrive\Desktop\Smart_Road_Safety_Project\data\indian_roads_dataset.csv")
df

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,visibility,temperature,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,low,32,high,weather,fatal,2,2,0,NaN,0.85
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,high,34,low,weather,major,4,3,0,NaN,0.10
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,low,21,medium,weather,minor,1,1,0,NaN,0.45
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,low,30,high,distraction,minor,5,2,0,NaN,0.65
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,high,24,low,distraction,minor,2,1,0,NaN,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,Bangalore,Karnataka,13.092276,77.599571,2022-09-29,3:00,3,Thursday,0,...,high,31,low,distraction,minor,3,2,0,NaN,0.10
19996,19996,Chennai,Tamil Nadu,13.172928,80.157062,2023-11-25,1:00,1,Saturday,1,...,high,20,low,distraction,major,4,2,0,NaN,0.10
19997,19997,Chennai,Tamil Nadu,12.997170,80.150724,2022-06-18,15:00,15,Saturday,1,...,high,22,low,weather,minor,3,3,0,NaN,0.10
19998,19998,Kolkata,West Bengal,22.454882,88.322213,2023-03-12,4:00,4,Sunday,1,...,high,33,low,poor road,minor,1,0,0,NaN,0.10
19999,19999,Delhi,Delhi,28.510266,77.065301,2024-07-05,23:00,23,Friday,0,...,low,39,high,overspeeding,minor,4,2,0,NaN,0.65

In [3]:
df.shape

(20000, 24)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   accident_id        20000 non-null  int64
 1   city               20000 non-null  object
 2   state              20000 non-null  object
 3   latitude           20000 non-null  float64
 4   longitude          20000 non-null  float64
 5   date               20000 non-null  object
 6   time               20000 non-null  object
 7   hour               20000 non-null  int64
 8   day_of_week        20000 non-null  object
 9   is_weekend         20000 non-null  int64
 10  road_type          20000 non-null  object
 11  lanes              20000 non-null  int64
 12  traffic_signal     20000 non-null  int64
 13  weather            20000 non-null  object
 14  visibility         20000 non-null  object
 15  temperature        20000 non-null  int64
 16  traffic_density    20000 non-null  object
 17  cause              20000 non-null  object
 18  accident_severity  20000 non-null  object
 19  vehicles_involved  20000 non-null  int64
 20  casualties         20000 non-null  int64
 21  is_peak_hour       20000 non-null  int64
 22  festival           115 non-null    object
 23  risk_score         20000 non-null  float64
dtypes: float64(3), int64(9), object(12)
memory usage: 3.7+ MB

In [5]:
df.isnull().sum()

accident_id              0
city                     0
state                    0
latitude                 0
longitude                0
date                     0
time                     0
hour                     0
day_of_week              0
is_weekend               0
road_type                0
lanes                    0
traffic_signal           0
weather                  0
visibility               0
temperature              0
traffic_density          0
cause                    0
accident_severity        0
vehicles_involved        0
casualties               0
is_peak_hour             0
festival             19885
risk_score               0
dtype: int64

In [6]:
df.dtypes

accident_id            int64
city                  object
state                 object
latitude             float64
longitude            float64
date                  object
time                  object
hour                   int64
day_of_week           object
is_weekend             int64
road_type             object
lanes                  int64
traffic_signal         int64
weather               object
visibility            object
temperature            int64
traffic_density       object
cause                 object
accident_severity     object
vehicles_involved      int64
casualties             int64
is_peak_hour           int64
festival              object
risk_score           float64
dtype: object

In [7]:
df.describe()

,accident_id,latitude,longitude,hour,is_weekend,lanes,traffic_signal,temperature,vehicles_involved,casualties,is_peak_hour,risk_score
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,9999.500000,20.389207,78.173330,11.487200,0.286150,3.493950,0.499850,27.579600,2.992000,1.726450,0.247400,0.437585
std,5773.647028,6.165791,4.485967,6.945563,0.451972,1.705406,0.500012,7.454746,1.415534,1.489104,0.431512,0.218130
min,0.000000,12.800172,72.700017,0.000000,0.000000,1.000000,0.000000,15.000000,1.000000,0.000000,0.000000,0.100000
25%,4999.750000,13.198653,73.997979,5.000000,0.000000,2.000000,0.000000,21.000000,2.000000,1.000000,0.000000,0.250000
50%,9999.500000,18.812008,77.297000,12.000000,0.000000,4.000000,0.000000,28.000000,3.000000,1.000000,0.000000,0.450000
75%,14999.250000,28.402467,80.111089,18.000000,1.000000,5.000000,1.000000,34.000000,4.000000,3.000000,0.000000,0.600000
max,19999.000000,30.799960,88.499861,23.000000,1.000000,6.000000,1.000000,40.000000,5.000000,5.000000,1.000000,1.000000

In [8]:
df.columns

Index(['accident_id', 'city', 'state', 'latitude', 'longitude', 'date', 'time',
       'hour', 'day_of_week', 'is_weekend', 'road_type', 'lanes',
       'traffic_signal', 'weather', 'visibility', 'temperature',
       'traffic_density', 'cause', 'accident_severity', 'vehicles_involved',
       'casualties', 'is_peak_hour', 'festival', 'risk_score'],
      dtype='object')

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
for col in df.select_dtypes(include='object').columns:
    print(col, df[col].nunique())

city 8
state 7
date 1201
time 24
day_of_week 7
road_type 3
weather 3
visibility 3
traffic_density 3
cause 5
accident_severity 3
festival 4

In [12]:
d_types=dict(df.dtypes)
for name,type_ in d_types.items():
    if str(type_)=="object":
        print(f"<============{name}=============>")
        print(df[name].value_counts())

<============city=============>
city
Chandigarh    2577
Chennai       2575
Kolkata       2559
Pune          2517
Mumbai        2492
Bangalore     2438
Delhi         2433
Hyderabad     2409
Name: count, dtype: int64
<============state=============>
state
Maharashtra    5009
Punjab         2577
Tamil Nadu     2575
West Bengal    2559
Karnataka      2438
Delhi          2433
Telangana      2409
Name: count, dtype: int64
<============date=============>
date
2022-11-03    30
2023-10-02    29
2024-12-21    28
2023-10-09    28
2023-11-25    28
              ..
2025-04-02     7
2024-04-03     7
2023-09-09     6
2024-05-02     5
2024-10-21     5
Name: count, Length: 1201, dtype: int64
<============time=============>
time
2:00     888
13:00    878
12:00    866
17:00    861
1:00     859
6:00     856
22:00    853
8:00     849
11:00    841
19:00    840
0:00     840
14:00    838
20:00    838
21:00    830
5:00     827
23:00    825
3:00     824
18:00    823
15:00    811
4:00     805
10:00    789
16:00    787
9:00     786
7:00     786
Name: count, dtype: int64
<============day_of_week=============>
day_of_week
Monday       2966
Friday       2879
Tuesday      2871
Saturday     2867
Sunday       2856
Thursday     2835
Wednesday    2726
Name: count, dtype: int64
<============road_type=============>
road_type
urban      6745
rural      6639
highway    6616
Name: count, dtype: int64
<============weather=============>
weather
clear    6690
rain     6677
fog      6633
Name: count, dtype: int64
<============visibility=============>
visibility
low       9987
high      6690
medium    3323
Name: count, dtype: int64
<============traffic_density=============>
traffic_density
low       7067
high      7034
medium    5899
Name: count, dtype: int64
<============cause=============>
cause
distraction      4026
overspeeding     4025
weather          3997
drunk driving    3978
poor road        3974
Name: count, dtype: int64
<============accident_severity=============>
accident_severity
minor    11025
major     5988
fatal     2987
Name: count, dtype: int64
<============festival=============>
festival
Holi        38
Eid         34
Diwali      31
New Year    12
Name: count, dtype: int64